# Generated by Django 4.1 on 2022-09-15 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('symbol', models.CharField(max_length=1, unique=True, verbose_name='Symbol')),
                ('short', models.CharField(max_length=3, unique=True, verbose_name='Short')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(unique=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Date',
                'verbose_name_plural': 'Dates',
            },
        ),
        migrations.CreateModel(
            name='RatesUSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=16, max_digits=32, verbose_name='Rate')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usd_rates', to='dashboard.currency', verbose_name='Currency')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usd_rates', to='dashboard.date', verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Rate USD',
                'verbose_name_plural': 'Rates USD',
            },
        ),
        migrations.AddField(
            model_name='date',
            name='date_currency_rate',
            field=models.ManyToManyField(through='dashboard.RatesUSD', to='dashboard.currency'),
        ),
    ]
